# Generated by Django 3.0.6 on 2020-09-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultRender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toggle', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
