# Generated by Django 3.0.6 on 2020-09-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_resultrender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultrender',
            name='toggle',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
