# Generated by Django 3.0.6 on 2020-09-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200905_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultrender',
            name='toggle',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
