# Generated by Django 3.0.6 on 2020-09-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20200908_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('FACULTY OF SCIENCE', 'FACULTY OF SCIENCE'), ('FACULTY OF ENGINEERING', 'FACULTY OF ENGINEERING'), ('FACULTY OF BASIC MEDICAL SCIENCES', 'FACULTY OF BASIC MEDICAL SCIENCES'), ('FACULTY OF BUSINESS AND SOCIAL SCIENCES', 'FACULTY OF BUSINESS AND SOCIAL SCIENCES'), ('FACULTY OF ART', 'FACULTY OF ART'), ('FACULTY OF LAW', 'FACULTY OF LAW')], max_length=100),
        ),
    ]
