# Set the build language to Python
language:
    python
after_success:
    - bash <(curl -s https://codecov.io/bash)

# Disable sudo to speed up the build
sudo: false

# Set the python version to 3.8
python: 3.8

services: # => 3 
    - postgresql
env: # => 4
    -DJANGO=3.1 DB=mysql

# Install the codecov pip dependency
install:
  - pip install -r requirements.txt

before_script: # => 6
    - postgresql -e 'create database test;' -u root

# Run the unit test
script:
  - python manage.py test

# Push the results back to codecov
after_success:
  - codecov